"""Optional model-assisted review for codbeing reports."""

from __future__ import annotations

import json
import urllib.error
import urllib.request
from collections.abc import Mapping, Sequence
from typing import Any

from .config import CodbeingConfig, _glm_api_key, glm_runtime_env


def model_assist_section(
    traces: Sequence[Mapping[str, Any]],
    report: str,
    config: CodbeingConfig,
    provider: str,
    consent_granted: bool = False,
    assist_requested: bool = False,
) -> list[str]:
    """Return a Markdown section describing the selected execution model.

    External providers receive the complete supplied evidence only after the
    caller has requested assist and recorded explicit consent. The default
    keeps evidence local.
    """
    if provider == "glm":
        return _glm_assist_section(
            traces,
            report,
            config,
            consent_granted,
            assist_requested,
        )
    return [
        "## Model Assist",
        "- Selected model: **codex/local**.",
        "- Status: external model calls are disabled; report generated by local "
        "evidence-grounded codbeing logic.",
        "",
    ]


def _glm_assist_section(
    traces: Sequence[Mapping[str, Any]],
    report: str,
    config: CodbeingConfig,
    consent_granted: bool,
    assist_requested: bool,
) -> list[str]:
    model = config.glm_model.strip()
    if not assist_requested:
        return [
            "## Model Assist",
            f"- Selected model: **GLM ({model or 'not configured'})**.",
            "- Status: external assist was not started because no explicit LLM assist "
            "action was requested.",
            "- Use `--model glm` to request external assist; local Runtime Analysis "
            "remains available without external context sharing.",
            "",
        ]

    if not model:
        return [
            "## Model Assist",
            "- Selected provider: **GLM**.",
            "- Status: no GLM model is configured. Local Runtime Analysis was generated "
            "without sending trace data externally.",
            "- Choose a model with `cb model use glm --glm-model <model>` before "
            "requesting GLM assist.",
            "",
        ]

    api_key = _glm_api_key()
    if api_key is None or not api_key.strip():
        return [
            "## Model Assist",
            f"- Selected model: **GLM ({model})**.",
            "- Status: GLM API key was not found. Local Runtime Analysis was generated "
            "without sending trace data externally.",
            "- Expected key env var: `CODBEING_GLM_API_KEY`, `GLM_API_KEY`, or "
            "`ZHIPUAI_API_KEY`.",
            "",
        ]
    api_key = api_key.strip()

    if not consent_granted:
        return [
            "## Model Assist",
            f"- Selected model: **GLM ({model})**.",
            "- Status: external assist was not started because consent to send the "
            "full DecisionTrace and report body was not granted.",
            "- Local Runtime Analysis remains available without external context sharing.",
            "",
        ]

    try:
        review = _call_glm(
            traces,
            report,
            config,
            api_key,
            consent_granted=True,
            assist_requested=True,
        )
    except (
        OSError,
        urllib.error.URLError,
        TimeoutError,
        json.JSONDecodeError,
        KeyError,
    ) as error:
        return [
            "## Model Assist",
            f"- Selected model: **GLM ({model})**.",
            "- Status: GLM call failed; local Runtime Analysis is still available.",
            f"- Error: {_safe_error(error)}.",
            "",
        ]

    return [
        "## Model Assist",
        f"- Selected model: **GLM ({model})**.",
        "- Status: GLM returned an evidence-bound review.",
        "",
        review,
        "",
    ]


def external_assist_ready(config: CodbeingConfig, provider: str) -> bool:
    """Return whether an external provider is configured enough to request consent."""
    api_key = _glm_api_key()
    return (
        provider == "glm"
        and bool(config.glm_model.strip())
        and api_key is not None
        and bool(api_key.strip())
    )


def _call_glm(
    traces: Sequence[Mapping[str, Any]],
    report: str,
    config: CodbeingConfig,
    api_key: str,
    *,
    consent_granted: bool,
    assist_requested: bool = False,
) -> str:
    """Send raw evidence only after an explicit assist action and consent."""
    _require_external_assist_consent(
        consent_granted=consent_granted,
        assist_requested=assist_requested,
    )

    prompt = (
        "You are a codbeing Runtime Analysis reviewer. Review the report using only "
        "the supplied DecisionTrace JSON and report text. Do not infer hidden motives, "
        "do not give life commands, and do not predict external success. Return at "
        "most five concise bullets about evidence quality, missing signals, and "
        "one optional next trace to capture.\n\n"
        f"DecisionTrace JSON:\n{json.dumps(list(traces), ensure_ascii=False)}\n\n"
        f"Report:\n{report}"
    )
    runtime_env = glm_runtime_env()
    if runtime_env.get("ANTHROPIC_BASE_URL") and runtime_env.get("ANTHROPIC_AUTH_TOKEN"):
        return _call_glm_anthropic_compatible(
            prompt,
            runtime_env,
            consent_granted=consent_granted,
            assist_requested=assist_requested,
        )

    payload = {
        "model": config.glm_model,
        "messages": [
            {"role": "system", "content": "You review evidence-bound personal runtime reports."},
            {"role": "user", "content": prompt},
        ],
        "temperature": 0.2,
    }
    request = urllib.request.Request(
        config.glm_base_url,
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    with urllib.request.urlopen(request, timeout=45) as response:
        data = json.loads(response.read().decode("utf-8"))
    content = data["choices"][0]["message"]["content"]
    return str(content).strip()


def _require_external_assist_consent(
    *, consent_granted: bool, assist_requested: bool
) -> None:
    """Reject outbound research material unless assist and sharing were confirmed."""
    if not assist_requested:
        raise PermissionError(
            "An explicit LLM assist action is required before sending raw research material."
        )
    if not consent_granted:
        raise PermissionError(
            "Explicit consent is required before sending raw research material externally."
        )

def _call_glm_anthropic_compatible(
    prompt: str,
    runtime_env: Mapping[str, str],
    *,
    consent_granted: bool,
    assist_requested: bool,
) -> str:
    _require_external_assist_consent(
        consent_granted=consent_granted,
        assist_requested=assist_requested,
    )
    base_url = runtime_env["ANTHROPIC_BASE_URL"].rstrip("/")
    endpoint = base_url if base_url.endswith("/v1/messages") else f"{base_url}/v1/messages"
    token = runtime_env["ANTHROPIC_AUTH_TOKEN"]
    model = runtime_env.get("ANTHROPIC_DEFAULT_SONNET_MODEL") or runtime_env.get(
        "ANTHROPIC_MODEL"
    ) or "GLM-5"
    payload = {
        "model": model,
        "max_tokens": 900,
        "temperature": 0.2,
        "system": "You review evidence-bound personal runtime reports.",
        "messages": [{"role": "user", "content": prompt}],
    }
    request = urllib.request.Request(
        endpoint,
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {token}",
            "x-api-key": token,
            "anthropic-version": "2023-06-01",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    with urllib.request.urlopen(request, timeout=45) as response:
        data = json.loads(response.read().decode("utf-8"))
    content = data["content"][0]
    if isinstance(content, dict):
        return str(content.get("text", "")).strip()
    return str(content).strip()


def _safe_error(error: BaseException) -> str:
    text = str(error).replace("\n", " ").strip()
    if len(text) > 160:
        return f"{text[:160].rstrip()}..."
    return text or error.__class__.__name__
